logging:
  level:
    org:
      springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: restful-web-service

  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true

  jpa:
    defer-datasource-initialization: true
    show-sql: true
