logging:
  level:
    org:
      springframework: info

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: restful-web-service

  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:mysql://localhost:3306/social_media_application
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  h2:
    console:
      enabled: true

  security:
    user:
      name: root
      password: password

  jpa:
    defer-datasource-initialization: true
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
